[mypy]
python_version = 3.13
strict = True
ignore_missing_imports = True
mypy_path = ..

[mypy-tests.*]
strict = False
disable_error_code = no-untyped-def, no-untyped-call, method-assign, assignment

[mypy-backend.tests.*]
strict = False
disable_error_code = no-untyped-def, no-untyped-call, method-assign, assignment
