import React from 'react';
import { HelpCircle } from 'lucide-react';
import LoadingSpinner from '../shared/LoadingSpinner';

/** Panel title shown on the volunteer explanation drawer. */
const PANEL_TITLE = 'GenAI Jargon-Free Guide (New Volunteer Mode)';

/**
 * ExplainAlertButton — Inline expandable drawer that shows a volunteer-friendly
 * plain-text explanation of an alert, generated by the AI orchestrator.
 *
 * Renders a trigger button first. When active (`isExplaining` or `explanation`),
 * a drawer expands below the alert card with a spinner or the rendered explanation.
 *
 * @param {Object}   alert        - The alert object to explain (must have incident_id).
 * @param {string}   language     - Target language for the AI-generated explanation.
 * @param {Function} onExplain    - Callback invoked when the trigger button is clicked.
 * @param {boolean}  isExplaining - True while the AI explanation is being fetched.
 * @param {string}   explanation  - The returned AI explanation text, or empty string.
 * @param {Function} onDismiss    - Callback to close the explanation drawer.
 */
export default function ExplainAlertButton({
  alert,
  language,
  onExplain,
  isExplaining,
  explanation,
  onDismiss
}) {
  return (
    <div className="mt-4 pt-3.5 border-t border-slate-800 flex flex-col gap-2 relative">
      <button
        onClick={() => onExplain(alert, language)}
        className="w-full bg-slate-950 hover:bg-slate-900 border border-slate-800 text-slate-300 text-xs py-2 px-4 rounded-xl flex items-center justify-center gap-1.5 transition font-semibold"
        aria-label="Get plain-language volunteer explanation for this alert"
      >
        <HelpCircle className="w-4 h-4 text-indigo-400" aria-hidden="true" />
        {PANEL_TITLE}
      </button>

      {isExplaining && (
        <div className="mt-2.5 bg-slate-950/80 border border-slate-800/80 rounded-xl p-3.5 relative flex flex-col gap-1.5 animate-fadeIn">
          <h5 className="text-xs font-bold text-white flex items-center gap-1.5">
            <HelpCircle className="w-3.5 h-3.5 text-indigo-400" aria-hidden="true" />
            {PANEL_TITLE}
          </h5>
          <LoadingSpinner text={`Drafting plain-text guidance in ${language}...`} />
          <button
            onClick={onDismiss}
            className="absolute top-3 right-3 text-[10px] text-slate-500 hover:text-slate-300"
            aria-label="Dismiss explanation panel"
          >
            Dismiss
          </button>
        </div>
      )}

      {explanation && !isExplaining && (
        <div className="mt-2.5 bg-slate-950/80 border border-slate-800/80 rounded-xl p-3.5 relative flex flex-col gap-1.5 animate-fadeIn">
          <h5 className="text-xs font-bold text-white flex items-center gap-1.5">
            <HelpCircle className="w-3.5 h-3.5 text-indigo-400" aria-hidden="true" />
            {PANEL_TITLE}
          </h5>
          <p className="text-xs text-slate-300 leading-relaxed whitespace-pre-line">
            {explanation}
          </p>
          <button
            onClick={onDismiss}
            className="absolute top-3 right-3 text-[10px] text-slate-500 hover:text-slate-300"
            aria-label="Dismiss explanation panel"
          >
            Dismiss
          </button>
        </div>
      )}
    </div>
  );
}
